import static spark.Spark.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        webSocket("/socket", WebSocketHandler.class);
        staticFileLocation("static");
        port(8080);
        init();
    }
}
